pygments: true
auto: true
url: http://blog.xmi.im
lsi: false
markdown: redcarpet

colors:
  highlight: '#f60'

projects:
  - year: 2013
    projects:
      - name: URL Shortener
        url: http://gid.im
        blurb: URL Shortener

      - name: Stringer
        url: https://github.com/gindis/stringer
        blurb: A self-hosted, anti-social RSS reader

tools:
  - category: FD
    tools:
      - name: NODEJS
        url: http://nodejs.org
        blurb: Node.js is a platform built on Chrome's JavaScript runtime for easily building fast scalable network applications.
      - name: EXPRESSJS
        url: http://expressjs.com
        blurb: web application framework for node
      - name: ANGULARJS
        url: http://angularjs.org
        blurb: HTML enhanced for web apps!
      - name: React
        url: http://facebook.github.io/react
        blurb: A JAVASCRIPT LIBRARY FOR BUILDING USER INTERFACES
      - name: Hogan.js
        url: http://twitter.github.io/hogan.js
        blurb: JavaScript templating from Twitter.
      - name: SASS
        url: http://sass-lang.com
        blurb: CSS with superpowers.
      - name: Ionic
        url: http://ionicframework.com
        blurb: The bond between HTML5 and Native has arrived.
      - name: YEOMAN
        url: http://yeoman.io
        blurb: MODERN WORKFLOWS FOR MODERN WEBAPPS
      - name: Frontend Development
        url: https://github.com/dypsilon/frontend-dev-bookmarks
        blurb: frontend-dev-bookmarks

  - category: UI
    tools:
      - name: Font Awesome
        url: http://fontawesome.io
        blurb: The iconic font designed for Bootstrap
      - name: Responsive Resources
        url: http://bradfrost.github.io/this-is-responsive/resources.html
        blurb: A collection of resources about the various aspects of responsive web design.

  - category: Mac
    tools:
      - name: Homebrew
        url: http://brew.sh
        blurb: The missing package manager for OS X

